export const DOMAINS=['people','process','business-environment'];
export function domain(q){return DOMAINS.find(d=>q.tags?.includes(d))||({People:'people',Process:'process','Business Environment':'business-environment'}[q.section?.name])||'other'}
export function grade(q,response){if(!Array.isArray(q.correctAnswer)||!q.correctAnswer.length)return null;return JSON.stringify([...q.correctAnswer].sort())===JSON.stringify([...response].sort())}
export function shuffle(items,rng=Math.random){let a=[...items];for(let i=a.length-1;i>0;i--){let j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
export function planExam(questions,rng=Math.random){const quotas=[59,74,47];let selected=[];for(let i=0;i<3;i++){let pool=questions.filter(q=>domain(q)===DOMAINS[i]&&q.examEligible!==false&&(q.hasKey??!!q.correctAnswer?.length));if(pool.length<quotas[i])throw Error(`Chưa đủ câu cho ${DOMAINS[i]}`);selected.push(...shuffle(pool,rng).slice(0,quotas[i]))}return shuffle(selected,rng)}
export function validatePack(p){if(p?.format!=='pmp-study-v1'||!Array.isArray(p.questions)||p.questions.length>20000||!Array.isArray(p.lessons)||p.lessons.length>200)throw Error('Gói dữ liệu không hợp lệ');let ids=new Set();for(let q of p.questions){if(typeof q.id!=='string'||ids.has(q.id)||typeof q.content?.prompt!=='string'||!Array.isArray(q.choices))throw Error('Cấu trúc câu hỏi không hợp lệ');ids.add(q.id);const choices=new Set(q.choices.map(c=>c.id));if(choices.size!==q.choices.length||q.choices.some(c=>typeof c.text!=='string'))throw Error('Phương án không hợp lệ');if(q.correctAnswer!==null&&(!Array.isArray(q.correctAnswer)||q.correctAnswer.some(a=>!choices.has(a))))throw Error('Đáp án không hợp lệ')}for(let l of p.lessons)if(typeof l.id!=='string'||typeof l.title!=='string'||typeof l.html!=='string')throw Error('Bài đọc không hợp lệ');return p}
export function mergeCourse(pack,course){if(!Array.isArray(course?.lessons)||course.lessons.length>200)throw Error('Chọn course-data.json của khóa study');let lessons=[],questions=pack.questions.filter(q=>q.sourceGroup!=='study');for(let l of course.lessons){if(!Number.isInteger(l.index)||typeof l.html!=='string'||typeof l.title!=='string'||!Array.isArray(l.quiz?.questions))throw Error('Bài học không hợp lệ');lessons.push({id:`study-${l.index}`,title:l.title,week:l.week,html:l.html,url:l.url});for(let q of l.quiz.questions){const options=q.options||[];let tail=q.body?.split('Kéo các mục để sắp xếp lại, hoặc dùng nút mũi tên')[1]||'',items=tail.split(/\n\s*\d+\s*\n/).map(s=>s.trim()).filter(Boolean);let n=Number(q.body?.match(/Đã ghép \d+\/(\d+)/)?.[1]),parts=(q.body?.split('Bước 1: Chọn câu hỏi bên TRÁI trước')[1]||'').replace(/Đã ghép[\s\S]*/,'').split(/\n\s*\n/).map(s=>s.trim()).filter(Boolean);questions.push({id:`study-${l.index}-${q.order}`,sourceGroup:'study',lessonId:`study-${l.index}`,type:q.kind==='choice'?'multiple_choice':q.kind,content:{prompt:q.stem||q.body},choices:options.map((text,i)=>({id:String(i),text})),correctAnswer:null,hint:q.hint,body:q.body,orderItems:items,matchLeft:parts.slice(0,n),matchRight:parts.slice(n),examEligible:false,tags:[],section:{name:'study'}})}}return validatePack({...pack,lessons,questions})}
export function remaining(session,now=Date.now()){return Math.max(0,Math.ceil((session.deadline-now)/1000))}
export function summarize(session,questions){let byId=new Map(questions.map(q=>[q.id,q])),domains={},correct=0,scored=0;for(let id of session.ids){let q=byId.get(id);if(!q)continue;let result=grade(q,session.responses[id]||[]);if(result===null)continue;scored++;if(result)correct++;let d=domain(q);domains[d]??={correct:0,total:0};domains[d].total++;if(result)domains[d].correct++}return {correct,scored,percent:scored?Math.round(correct/scored*100):null,domains}}
export function validateProgress(p){
 if(p?.format!=='pmp-progress-v1'||!p.state||typeof p.state!=='object'||Array.isArray(p.state))throw Error('Bản sao tiến độ không hợp lệ');
 const s=p.state,ids=a=>Array.isArray(a)&&a.length<=20000&&a.every(v=>typeof v==='string'),object=v=>v&&typeof v==='object'&&!Array.isArray(v),integer=v=>Number.isInteger(v)&&v>=0;
 if(!Array.isArray(s.history)||s.history.length>100||!ids(s.done)||!ids(s.bookmarks)||!object(s.notes)||Object.values(s.notes).some(n=>typeof n!=='string')||(s.locale!==undefined&&!['vi','en'].includes(s.locale)))throw Error('Tiến độ không hợp lệ');
 for(const h of s.history){if(!object(h)||!['practice','exam'].includes(h.mode)||!Number.isFinite(h.date)||!integer(h.durationSeconds)||!integer(h.correct)||!integer(h.scored)||h.correct>h.scored||!(h.percent===null||integer(h.percent)&&h.percent<=100)||!ids(h.answeredIds)||!ids(h.wrongIds)||!object(h.domains)||Object.values(h.domains).some(d=>!object(d)||!integer(d.correct)||!integer(d.total)||d.correct>d.total))throw Error('Lịch sử không hợp lệ')}
 if(s.session){const x=s.session;if(!ids(x.ids)||!x.ids.length||new Set(x.ids).size!==x.ids.length||!integer(x.index)||x.index>=x.ids.length||!object(x.responses)||Object.values(x.responses).some(v=>!ids(v))||!ids(x.flags)||!['practice','exam'].includes(x.mode)||!Number.isFinite(x.started)||x.mode==='exam'&&!Number.isFinite(x.deadline))throw Error('Phiên học không hợp lệ')}
 return s
}
const toB64=bytes=>{let s='';for(let b of bytes)s+=String.fromCharCode(b);return btoa(s)};
const fromB64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function keyFor(password,salt){let base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:310000},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
export async function encryptPack(pack,password){validatePack(pack);if(password.length<16)throw Error('Mật khẩu gói cần ít nhất 16 ký tự');let salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await keyFor(password,salt),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(pack)));return {format:'pmp-vault-v1',salt:toB64(salt),iv:toB64(iv),cipher:toB64(new Uint8Array(cipher))}}
export async function decryptPack(v,password){if(v?.format!=='pmp-vault-v1'||typeof v.cipher!=='string'||v.cipher.length>80000000)throw Error('Gói mã hóa không hợp lệ');try{let salt=fromB64(v.salt),iv=fromB64(v.iv);if(salt.length!==16||iv.length!==12)throw Error();let key=await keyFor(password,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,fromB64(v.cipher));return validatePack(JSON.parse(new TextDecoder().decode(plain)))}catch(e){throw Error('Không mở được gói: sai mật khẩu hoặc dữ liệu hỏng')}}
