import {$,esc,fmt,stat,evidence,horizontalBars,lineChart,mean,tooltipify} from "/apps/public-signals/charts.js";

const CITIES=["Tokyo","Seoul","Taipei","Bangkok","Singapore","Shanghai"];
const CITY_COORDS={Tokyo:[35.6762,139.6503],Seoul:[37.5665,126.978],Taipei:[25.033,121.5654],Bangkok:[13.7563,100.5018],Singapore:[1.3521,103.8198],Shanghai:[31.2304,121.4737]};
const COLORS={Tokyo:"#7c8cff",Seoul:"#36c5f0",Taipei:"#45c48b",Bangkok:"#ff8a4c",Singapore:"#ef5b68",Shanghai:"#b67cff"};
const prompts=["Which city had the worst PM2.5 in the last 30 days?","Compare summer temperatures across cities.","Which city had the most rainy days?","How often was AQI unhealthy?","Compare Tokyo and Seoul temperature."];
let rows=[],meta={},byCity={},currentConditions={},weatherLastFetch=0,airLastFetch=0;
const latestMs=()=>new Date(meta.climate.date_max+"T00:00:00Z").getTime();
const windowRows=days=>rows.filter(r=>new Date(r.date+"T00:00:00Z").getTime()>=latestMs()-(days-1)*86400000);

function colorScale(value,min,max,type){const t=Math.max(0,Math.min(1,(value-min)/Math.max(.001,max-min)));if(type==='temperature_mean')return `hsl(${220-t*205} 78% ${58-t*5}%)`;if(type==='pm2_5')return `hsl(${155-t*145} 72% ${51-t*5}%)`;return `hsl(${215-t*25} 78% ${74-t*30}%)`;}
function rolling(values,window=30){return values.map((row,i)=>({date:row.date,value:mean(values.slice(Math.max(0,i-window+1),i+1).map(r=>r.temperature_mean))}));}

function renderClimatePositioning(){
  const host=$("#climatePositionChart"),compact=matchMedia('(max-width: 620px)').matches,W=compact?620:1000,H=compact?500:480,L=72,R=42,T=28,B=58;
  const values=CITIES.map(city=>{const cityRows=byCity[city];return {city,temperature:mean(cityRows.map(row=>row.temperature_mean)),pm25:mean(cityRows.map(row=>row.pm2_5)),rainyDays:cityRows.filter(row=>row.precipitation_mm>=1).length};});
  const median=items=>{const sorted=items.slice().sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return (sorted[middle-1]+sorted[middle])/2;};
  const xMin=Math.floor(Math.min(...values.map(d=>d.temperature))-2),xMax=Math.ceil(Math.max(...values.map(d=>d.temperature))+2),yMin=Math.max(0,Math.floor(Math.min(...values.map(d=>d.pm25))-4)),yMax=Math.ceil(Math.max(...values.map(d=>d.pm25))+4),rainMax=Math.max(...values.map(d=>d.rainyDays));
  const x=value=>L+(value-xMin)/(xMax-xMin)*(W-L-R),y=value=>T+(yMax-value)/(yMax-yMin)*(H-T-B),xMedian=median(values.map(d=>d.temperature)),yMedian=median(values.map(d=>d.pm25));
  const labels={Tokyo:[14,-12,'start'],Seoul:[-14,-12,'end'],Taipei:[14,22,'start'],Bangkok:[-14,-12,'end'],Singapore:[14,22,'start'],Shanghai:[-14,22,'end']};
  const xTicks=Array.from({length:5},(_,i)=>xMin+i*(xMax-xMin)/4),yTicks=Array.from({length:5},(_,i)=>yMin+i*(yMax-yMin)/4);
  host.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Annual mean temperature and PM2.5 comparison across six Asian cities">
    ${xTicks.map(tick=>`<line class="grid" x1="${x(tick)}" x2="${x(tick)}" y1="${T}" y2="${H-B}"/><text class="axis" text-anchor="middle" x="${x(tick)}" y="${H-30}">${fmt(tick)}°C</text>`).join('')}
    ${yTicks.map(tick=>`<line class="grid" x1="${L}" x2="${W-R}" y1="${y(tick)}" y2="${y(tick)}"/><text class="axis" text-anchor="end" x="${L-9}" y="${y(tick)+3}">${fmt(tick)}</text>`).join('')}
    <line x1="${x(xMedian)}" x2="${x(xMedian)}" y1="${T}" y2="${H-B}" stroke="var(--portfolio-border-strong)" stroke-dasharray="5 5"/><line x1="${L}" x2="${W-R}" y1="${y(yMedian)}" y2="${y(yMedian)}" stroke="var(--portfolio-border-strong)" stroke-dasharray="5 5"/>
    <text class="axis" text-anchor="middle" x="${(L+W-R)/2}" y="${H-7}">ANNUAL MEAN TEMPERATURE</text><text class="axis" x="${L}" y="14">MEAN PM2.5 · µg/m³</text>
    ${values.map(item=>{const px=x(item.temperature),py=y(item.pm25),radius=8+item.rainyDays/rainMax*11,[dx,dy,anchor]=labels[item.city];return `<g><circle class="tooltip-target" data-tip="<b>${item.city}</b>${fmt(item.temperature)}°C · ${fmt(item.pm25)} µg/m³ PM2.5 · ${item.rainyDays} rainy days" cx="${px}" cy="${py}" r="${radius}" fill="var(--signal-violet)" fill-opacity=".72" stroke="var(--portfolio-surface)" stroke-width="2"/><line x1="${px}" y1="${py}" x2="${px+dx*.65}" y2="${py+dy*.65}" stroke="var(--portfolio-border-strong)"/><text class="chart-label" text-anchor="${anchor}" x="${px+dx}" y="${py+dy}">${item.city}</text><text class="value" text-anchor="${anchor}" x="${px+dx}" y="${py+dy+14}">${fmt(item.temperature)}° · ${fmt(item.pm25)}</text></g>`;}).join('')}
  </svg>`;tooltipify(host);
}

function renderFingerprint(metric="temperature_mean"){
  const host=$("#fingerprintChart"), W=1100,H=310,L=88,R=12,T=30,rowH=39,cellW=(W-L-R)/365;
  const vals=rows.map(r=>r[metric]).filter(Number.isFinite), min=metric==='precipitation_mm'?0:Math.min(...vals), max=metric==='temperature_mean'?Math.max(...vals):Math.min(Math.max(...vals),metric==='pm2_5'?80:60);
  const monthLabels=[]; const sample=byCity.Tokyo; let lastMonth=-1; sample.forEach((r,i)=>{const month=+r.date.slice(5,7);if(month!==lastMonth){monthLabels.push({i,label:new Date(r.date+'T00:00:00Z').toLocaleString('en',{month:'short'})});lastMonth=month;}});
  host.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Daily ${esc(metric)} heatmap by city">
    ${monthLabels.map(m=>`<text class="axis" x="${L+m.i*cellW}" y="17">${m.label}</text>`).join('')}
    ${CITIES.map((city,ci)=>`<text class="chart-label" x="0" y="${T+ci*rowH+20}">${city}</text>${byCity[city].map((r,i)=>`<rect class="tooltip-target" data-tip="<b>${city} · ${r.date}</b>${esc(metric.replaceAll('_',' '))}: ${fmt(r[metric])}" x="${L+i*cellW}" y="${T+ci*rowH}" width="${Math.max(1,cellW+.15)}" height="27" fill="${Number.isFinite(r[metric])?colorScale(Math.min(r[metric],max),min,max,metric):'var(--portfolio-border)'}"/>`).join('')}`).join('')}
    <text class="axis" x="${L}" y="${H-8}">LOW · ${fmt(min)}</text><text class="axis" text-anchor="end" x="${W-R}" y="${H-8}">HIGH · ${fmt(max)}${metric==='temperature_mean'?'°C':metric==='pm2_5'?' µg/m³':' mm'}</text>
  </svg>`;tooltipify(host);
}

function renderTrend(focus="Tokyo"){
  const series=CITIES.map(city=>({name:city,color:COLORS[city],focus:city===focus,values:rolling(byCity[city])}));
  lineChart($("#trendChart"),series,{label:"30-day rolling temperature by city",start:meta.climate.date_min,end:meta.climate.date_max});
  const legend=document.createElement('div');legend.className='legend';legend.innerHTML=CITIES.map(c=>`<span style="opacity:${c===focus?1:.5}"><i style="background:${COLORS[c]}"></i>${c}</span>`).join('');$("#trendChart").appendChild(legend);
}

function aggregate(metric,data=rows,mode="mean"){return CITIES.map(city=>{const cityRows=data.filter(r=>r.city===city),values=cityRows.map(r=>r[metric]).filter(Number.isFinite);return {label:city,value:mode==='count'?values.filter(v=>v).length:mean(values),rows:cityRows};}).sort((a,b)=>b.value-a.value);}
function renderAir(){const data=windowRows(30), rank=aggregate('pm2_5',data);const max=rank[0].value;$("#airRanking").innerHTML=rank.map((r,i)=>{const unhealthy=r.rows.filter(x=>x.aqi>100).length;return `<div class="rank-row"><span>${r.label}</span><span class="rank-track"><i class="rank-fill" style="width:${r.value/max*100}%;background:${i===0?'var(--signal-red)':'var(--signal-violet)'}"></i></span><span class="rank-value">${fmt(r.value)}<br>${unhealthy}d</span></div>`}).join('');}

const weatherLabel=code=>({0:"Clear",1:"Mainly clear",2:"Partly cloudy",3:"Overcast",45:"Fog",48:"Rime fog",51:"Light drizzle",53:"Drizzle",55:"Heavy drizzle",61:"Light rain",63:"Rain",65:"Heavy rain",71:"Light snow",73:"Snow",75:"Heavy snow",80:"Rain showers",81:"Rain showers",82:"Heavy showers",95:"Thunderstorm",96:"Storm + hail",99:"Storm + hail"}[code]||"Current weather");
function setCurrentStatus(message,state="live"){const host=$("#currentFreshness");host.className=`refresh-note live-refresh ${state==='loading'?'is-loading':state==='stale'?'is-stale':''}`;host.lastChild.textContent=message;}
function aqiLabel(value){if(!Number.isFinite(value))return "—";if(value<=50)return "Good";if(value<=100)return "Moderate";if(value<=150)return "Sensitive";if(value<=200)return "Unhealthy";return "Very unhealthy";}
function renderCurrentConditions(){
  $("#currentCities").innerHTML=CITIES.map(city=>{const item=currentConditions[city]||{},weather=item.weather||{},air=item.air||{};return `<article class="current-city"><div class="current-city-name">${city}</div><div class="current-city-temp">${Number.isFinite(weather.temperature_2m)?`${fmt(weather.temperature_2m)}°C`:"—"}</div><div class="current-city-feels">${Number.isFinite(weather.apparent_temperature)?`Feels ${fmt(weather.apparent_temperature)}° · ${weatherLabel(weather.weather_code)}`:"Weather loading…"}</div><div class="current-city-signals"><div class="current-city-signal"><span>Humidity</span><b>${Number.isFinite(weather.relative_humidity_2m)?`${fmt(weather.relative_humidity_2m,0)}%`:"—"}</b></div><div class="current-city-signal"><span>PM2.5</span><b>${Number.isFinite(air.pm2_5)?`${fmt(air.pm2_5)} µg/m³`:"—"}</b></div><div class="current-city-signal"><span>US AQI</span><b>${Number.isFinite(air.us_aqi)?`${fmt(air.us_aqi,0)} · ${aqiLabel(air.us_aqi)}`:"—"}</b></div></div></article>`;}).join('');
}
async function fetchCurrentForCity(city,kind){
  const [latitude,longitude]=CITY_COORDS[city],base=kind==="weather"?"https://api.open-meteo.com/v1/forecast":"https://air-quality-api.open-meteo.com/v1/air-quality",url=new URL(base);url.searchParams.set("latitude",latitude);url.searchParams.set("longitude",longitude);url.searchParams.set("timezone","auto");url.searchParams.set("current",kind==="weather"?"temperature_2m,apparent_temperature,relative_humidity_2m,wind_speed_10m,weather_code":"pm2_5,us_aqi");if(kind==="air")url.searchParams.set("domains","cams_global");const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error(`${city} ${kind}: ${response.status}`);const payload=await response.json();currentConditions[city]={...currentConditions[city],[kind]:payload.current||{}};
}
async function refreshCurrentConditions(kind,force=false){
  if(document.hidden)return;const now=Date.now(),last=kind==="weather"?weatherLastFetch:airLastFetch,minimumAge=kind==="weather"?55*60000:5.5*3600000;if(!force&&now-last<minimumAge)return;setCurrentStatus(`Updating ${kind==='weather'?'weather':'air quality'}…`,"loading");const results=await Promise.allSettled(CITIES.map(city=>fetchCurrentForCity(city,kind)));renderCurrentConditions();const succeeded=results.filter(result=>result.status==="fulfilled").length;if(succeeded){if(kind==="weather")weatherLastFetch=now;else airLastFetch=now;setCurrentStatus(`${kind==='weather'?'Weather':'Air quality'} checked just now · ${succeeded}/6 cities`);}else setCurrentStatus("Latest conditions unavailable · historical data remains available","stale");
}
function scheduleCurrentConditions(){refreshCurrentConditions("weather",true);refreshCurrentConditions("air",true);setInterval(()=>refreshCurrentConditions("weather"),3600000);setInterval(()=>refreshCurrentConditions("air"),6*3600000);document.addEventListener("visibilitychange",()=>{if(!document.hidden){refreshCurrentConditions("weather");refreshCurrentConditions("air");}});window.addEventListener("online",()=>{refreshCurrentConditions("weather",true);refreshCurrentConditions("air",true);});}

function analyze(question){
  const q=question.toLowerCase();let title,summary,method,chartTitle,chartSub,rank,metric,data=rows,valueLabel=v=>fmt(v);
  const summer=q.includes('summer');const last30=q.includes('30')||q.includes('last month');if(last30)data=windowRows(30);if(summer)data=rows.filter(r=>[6,7,8].includes(+r.date.slice(5,7)));
  if(q.includes('rain')){metric='precipitation_mm';rank=CITIES.map(city=>{const v=data.filter(r=>r.city===city);return {label:city,value:v.filter(r=>r.precipitation_mm>=1).length,total:mean(v.map(r=>r.precipitation_mm))}}).sort((a,b)=>b.value-a.value);title=`${rank[0].label} recorded the most rainy days`;summary=`${rank[0].label} had ${rank[0].value} days with at least 1 mm of precipitation in the common coverage window.`;method="Method · rainy day = daily precipitation ≥1 mm; fixed city coordinate, equal date coverage.";chartTitle="Rainy-day frequency";chartSub="Days with at least 1 mm precipitation";valueLabel=v=>`${fmt(v,0)} days`;
  }else if(q.includes('aqi')||q.includes('unhealthy')){metric='aqi';rank=CITIES.map(city=>({label:city,value:data.filter(r=>r.city===city&&r.aqi>100).length})).sort((a,b)=>b.value-a.value);title=`${rank[0].label} had the most unhealthy-AQI days`;summary=`${rank[0].label} exceeded US AQI 100 on ${rank[0].value} days. This uses daily maximum modelled AQI, so it captures short-lived peaks.`;method="Method · count of days with daily maximum US AQI >100; CAMS global model data, equal date window.";chartTitle="Days above AQI 100";chartSub="Daily maximum US AQI";valueLabel=v=>`${fmt(v,0)} days`;
  }else if(q.includes('temperature')||q.includes('summer')||q.includes('hot')){metric='temperature_mean';rank=aggregate(metric,data);if(q.includes('tokyo')&&q.includes('seoul'))rank=rank.filter(r=>['Tokyo','Seoul'].includes(r.label));title=`${rank[0].label} was warmer over the selected period`;summary=`${rank[0].label} averaged ${fmt(rank[0].value)}°C versus ${fmt(rank.at(-1).value)}°C in ${rank.at(-1).label}, a ${fmt(rank[0].value-rank.at(-1).value)}°C difference.`;method=`Method · arithmetic mean of daily mean temperature${summer?' for June–August':' over the shared coverage window'}; fixed city coordinates.`;chartTitle="Mean temperature";chartSub=summer?"June–August daily means":"Common-date daily means";valueLabel=v=>`${fmt(v)}°C`;
  }else{metric='pm2_5';rank=aggregate(metric,data);title=`${rank[0].label} had the highest PM2.5 exposure`;summary=`${rank[0].label} averaged ${fmt(rank[0].value)} µg/m³, ${fmt(rank[0].value/rank.at(-1).value)}× ${rank.at(-1).label}, the lowest city in this comparison.`;method=`Method · mean of daily PM2.5 values${last30?' over the last 30 complete days':' across the full coverage window'}; CAMS global model data.`;chartTitle="Mean PM2.5 by city";chartSub="Same dates and aggregation for all six cities";valueLabel=v=>`${fmt(v)} µg/m³`;}
  $("#answerTitle").textContent=title;$("#answerSummary").textContent=summary;$("#answerMethod").textContent=method;$("#answerChartTitle").textContent=chartTitle;$("#answerChartSub").textContent=chartSub;
  const best=rank[0],low=rank.at(-1);$("#answerEvidence").innerHTML=evidence([[valueLabel(best.value),`${best.label} · highest`],[valueLabel(low.value),`${low.label} · lowest`],[new Set(data.map(r=>r.date)).size.toLocaleString(),"days compared"],[`${rank.length} cities`,"same methodology"]]);horizontalBars($("#answerChart"),rank,{valueLabel,color:"var(--signal-violet)"});
}

async function boot(){const [data,m]=await Promise.all([fetch('/apps/public-signals/data/city-climate.json').then(r=>r.json()),fetch('/apps/public-signals/data/meta.json').then(r=>r.json())]);rows=data;meta=m;CITIES.forEach(c=>byCity[c]=rows.filter(r=>r.city===c).sort((a,b)=>a.date.localeCompare(b.date)));$("#freshness").textContent=`Historical baseline · ${m.climate.date_min} → ${m.climate.date_max} · ${m.climate.row_count.toLocaleString()} city-days`;const last=windowRows(30),hot=aggregate('temperature_mean',last)[0],dirty=aggregate('pm2_5',last)[0];$("#stats").innerHTML=[stat("Cities","6","Tokyo → Singapore"),stat("Coverage","365 days","equal date window"),stat("Warmest · 30d",hot.label,`${fmt(hot.value)}°C daily mean`),stat("Highest PM2.5 · 30d",dirty.label,`${fmt(dirty.value)} µg/m³ mean`)].join('');$("#prompts").innerHTML=prompts.map(p=>`<button class="prompt-chip" type="button">${esc(p)}</button>`).join('');$("#prompts").onclick=e=>{if(e.target.matches('button')){$("#askInput").value=e.target.textContent;analyze(e.target.textContent)}};$("#askForm").onsubmit=e=>{e.preventDefault();analyze($("#askInput").value||prompts[0])};$("#fingerprintMetric").onchange=e=>renderFingerprint(e.target.value);$("#cityFocus").innerHTML=CITIES.map(c=>`<option>${c}</option>`).join('');$("#cityFocus").onchange=e=>renderTrend(e.target.value);renderClimatePositioning();renderFingerprint();renderTrend();renderAir();analyze(prompts[0]);scheduleCurrentConditions();}
boot().catch(e=>{$("#freshness").textContent='Data unavailable';console.error(e)});
