import { useState } from "react";
import { ArrowSquareOut, CalendarBlank, ShieldCheck } from "@phosphor-icons/react";
import { SOURCES, isValidFilingDate, policyForFiling } from "../domain/policy";

const updates = [
  { agency: "ISA", date: "01 Apr 2027", status: "Published · future application", title: "New PR guideline / Hướng dẫn PR mới", en: "Published 1 Oct 2026; generally applies to filings from 1 Apr 2027. Income and public-burden sections also cover applications filed from 1 Apr 2026 that were pending on 1 Oct 2026.", vi: "Công bố 01/10/2026, áp dụng chung từ 01/04/2027. Riêng thu nhập và gánh nặng công còn áp dụng cho hồ sơ nộp từ 01/04/2026, đang xét ngày 01/10/2026.", source: "guideline", section: "§6" },
  { agency: "ISA", date: "01 Oct 2026", status: "In force", title: "PR approval fee / Lệ phí cấp PR", en: "Standard fee: ¥200,000, payable on approval. Applications accepted by 30 Sep 2026 retain ¥10,000. Qualifying reductions: ¥20,000; special residence-card issuance can add a fee.", vi: "Phí thông thường ¥200.000 khi được cấp. Hồ sơ tiếp nhận đến 30/09/2026 giữ mức ¥10.000; diện đủ điều kiện giảm còn ¥20.000. Thẻ cư trú tích hợp có thể phát sinh phí.", source: "application", section: "Fees" },
  { agency: "ISA", date: "01 Apr 2027", status: "Published · transition", title: "Three-year permit / Thời hạn cư trú 3 năm", en: "The blanket treatment of a 3-year permit as the longest period ends. A first filing after 1 Apr 2027 can qualify for transition only with a 3-year permit held on 31 Mar 2027 and a decision before that permit expires.", vi: "Chấm dứt việc mặc nhiên chấp nhận thời hạn 3 năm. Chuyển tiếp chỉ cho hồ sơ đầu tiên từ 01/04/2027, có thời hạn 3 năm ngày 31/03/2027 và được quyết định trước khi thời hạn đó hết.", source: "guideline", section: "§2.5(6), note 4" },
  { agency: "ISA", date: "01 Apr 2027", status: "Published · HSP", title: "70 / 80 points: review the full period", en: "The new text expressly requires continuous maintenance of 70+ for 3 years or 80+ for 1 year. Two endpoint calculations alone do not establish that history. The calculator remains a planning estimate.", vi: "Văn bản mới nêu rõ duy trì liên tục 70+ trong 3 năm hoặc 80+ trong 1 năm. Điểm tại hai đầu mốc chưa chứng minh toàn bộ thời gian. Cần rà soát các lần thay đổi lương, việc làm và điểm tuổi.", source: "guideline", section: "§3.6–7" },
  { agency: "ISA", date: "01 Apr 2027", status: "Published · family routes", title: "Spouse and child routes / Diện gia đình", en: "Spouse exception changes from 3 years of genuine marriage + 1 year in Japan to 5 + 3. Biological-child exception changes from 1 year in Japan to 3. These are separate from the HSP calculator.", vi: "Diện vợ/chồng đổi từ hôn nhân thực tế 3 năm + cư trú 1 năm thành 5 + 3; con ruột từ cư trú 1 năm thành 3. Đây là diện riêng với bộ tính HSP.", source: "guideline", section: "§3.1; previous guideline §2.1" },
  { agency: "ISA", date: "01 Apr 2027", status: "Published · review factors", title: "Language, family and residence history", en: "B1 Japanese is a review factor with stated exceptions, including qualifying highly skilled applicants and families. The guideline also addresses household finances, school-age children, understanding Japanese rules and extended absences. No automatic pass/fail is inferred here.", vi: "B1 là yếu tố xét với các ngoại lệ, gồm diện nhân lực chất lượng cao đủ điều kiện và gia đình. Hướng dẫn còn xét tài chính hộ, việc học của con, hiểu quy tắc Nhật và thời gian vắng mặt. Trang không tự suy ra đạt/trượt.", source: "guideline", section: "§2.4; §2.5(6)–(10)" },
  { agency: "ISA", date: "01 Apr 2027", status: "Published · finances", title: "Household income and pension evidence", en: "Income is assessed against the Japanese household average for the household size. Income from dependent-status holders' limited permitted work is excluded; supported relatives abroad count in household size. Pension prospects and possible compensating assets are separate review factors.", vi: "Thu nhập xét theo mức bình quân hộ Nhật cùng quy mô; không cộng thu nhập làm thêm theo phép ngoài tư cách của diện phụ thuộc. Người thân ở nước ngoài được nuôi dưỡng cũng tính vào quy mô hộ. Triển vọng lương hưu và tài sản bù đắp được xét riêng.", source: "guideline", section: "§2.4(2)–(3)" },
  { agency: "ISA", date: "01 Apr 2027", status: "Published · residence history", title: "Extended absences / Vắng mặt dài ngày", en: "Without a reasonable reason, one absence of 6 months or more, or total absences of 2 years 6 months or more within the past 10 years, normally receives a negative assessment. This is a review factor, not an automatic rejection rule.", vi: "Nếu không có lý do hợp lý, vắng từ 6 tháng trong một lần hoặc tổng từ 2 năm 6 tháng trong 10 năm trước ngày nộp thường bị đánh giá bất lợi. Đây là yếu tố xét, không tự động đồng nghĩa bị từ chối.", source: "guideline", section: "§2.5(6)" },
  { agency: "NPA", date: "01 Apr 2026", status: "In force", title: "Bicycle blue tickets / Vé xanh cho xe đạp", en: "The traffic-violation notification system covers cyclists aged 16+. Paying the notified administrative penalty prevents prosecution under this system. A criminal fine is different; ISA assesses conduct separately.", vi: "Áp dụng cho người đi xe đạp từ 16 tuổi. Nộp 反則金 theo thủ tục này thì không bị truy tố; khoản này khác 罰金 hình sự. ISA đánh giá hạnh kiểm riêng, không có bảo đảm miễn ảnh hưởng PR.", source: "police", section: "Traffic-violation notification system" },
  { agency: "NPA", date: "01 Oct 2025", status: "In force", title: "Foreign licence conversion / Đổi bằng lái", en: "Residence-address checks were tightened. The knowledge check increased from 10 to 50 questions and the pass standard from 70% to 90%; practical checks were strengthened. Check your prefectural police procedure and any applicable exemption.", vi: "Siết kiểm tra địa chỉ cư trú; kiểm tra kiến thức tăng từ 10 lên 50 câu, mức đạt từ 70% lên 90%; tăng kiểm tra kỹ năng. Xem thủ tục cảnh sát tỉnh và trường hợp được miễn.", source: "licence", section: "FY2026 traffic safety plan · foreign drivers" },
  { agency: "MOFA", date: "01 Jul 2026", status: "In force · overseas visa", title: "Consular visa fees / Phí visa tại lãnh sự", en: "For applications accepted from 1 Jul 2026: approximately ¥15,000 single entry or ¥30,000 multiple entry, collected in local currency. Nationality/purpose exemptions or different amounts may apply, plus agency handling fees.", vi: "Hồ sơ tiếp nhận từ 01/07/2026: khoảng ¥15.000 một lần hoặc ¥30.000 nhiều lần, thu bằng nội tệ. Có miễn/khác mức theo quốc tịch và mục đích; dịch vụ đại lý tính riêng.", source: "visa", section: "Announcement 24 Jun 2026" },
  { agency: "MOFA", date: "Checked 05 Oct 2026", status: "Authority boundary", title: "Visa, residence status and PR", en: "MOFA and diplomatic missions issue entry visas; immigration grants landing permission and manages residence status. An entry visa does not guarantee landing. PR applications in Japan follow ISA rules and fees.", vi: "MOFA/cơ quan đại diện cấp visa nhập cảnh; nhập cảnh và tư cách cư trú thuộc cơ quan xuất nhập cảnh. Visa không bảo đảm được nhập cảnh. Hồ sơ PR tại Nhật dùng quy định và lệ phí ISA.", source: "visaStatus", section: "Visas and landing permission" },
];

export function PolicyOverview({ assessmentDate, onDateChange }) {
  const [agency, setAgency] = useState("ISA");
  const policy = policyForFiling(assessmentDate);
  const handleDateInput = (event) => {
    const date = event.currentTarget.value;
    if (isValidFilingDate(date) && date !== assessmentDate) onDateChange(date);
  };
  return <section className="policy-overview" aria-labelledby="policy-title">
    <div className="policy-heading"><div><p className="policy-eyebrow"><ShieldCheck size={16} /> OFFICIAL SOURCE REVIEW · 05 OCT 2026</p><h1 id="policy-title">Plan your Japan PR application</h1><p>Lập kế hoạch vĩnh trú theo ngày nộp hồ sơ, điểm HSP và bằng chứng.</p></div><label className="filing-date"><span><CalendarBlank size={17} />Planned filing date / Ngày dự kiến nộp</span><input type="date" aria-label="Planned filing date" min="2025-04-01" value={assessmentDate} onInput={handleDateInput} onChange={handleDateInput} /><small>Enter all score inputs as of this date.<br />Nhập tuổi, lương và điều kiện tại đúng ngày này.</small></label></div>
    <div className="policy-summary">
      <article><span>STANDARD PR FEE · ISA</span><strong>¥{policy.standardFee.toLocaleString("en-US")}</strong><p>Payable on approval · Phí khi được cấp</p><a href={SOURCES.application} target="_blank" rel="noreferrer">Fee rules & reductions <ArrowSquareOut size={13} /></a></article>
      <article><span>GUIDELINE FOR YOUR FILING DATE</span><strong>{policy.revisedGuideline ? "2027 rules" : "Before Apr 2027"}</strong><p>{policy.revisedGuideline ? "Published revision applies · Hướng dẫn mới" : "Published changes start 01 Apr 2027"}</p><a href={policy.revisedGuideline ? SOURCES.guideline : SOURCES.previous} target="_blank" rel="noreferrer">Applicable guideline <ArrowSquareOut size={13} /></a></article>
      <article><span>HSP ASSESSMENT PATHS</span><strong>70 / 80 points</strong><p>3 years / 1 year · Evidence required</p><a href={SOURCES.hsp} target="_blank" rel="noreferrer">Route-specific documents <ArrowSquareOut size={13} /></a></article>
    </div>
    <details id="official-updates" className="official-updates"><summary>Official updates: ISA · Police · MOFA <span>Thông tin mới & thời điểm áp dụng</span></summary><div className="source-controls" role="group" aria-label="Filter official updates">{["ISA", "NPA", "MOFA"].map((item) => <button type="button" key={item} aria-pressed={agency === item} onClick={() => setAgency(item)}>{item === "NPA" ? "Police / Cảnh sát" : item}</button>)}</div><div className="update-grid">{updates.filter((item) => item.agency === agency).map((item) => <article key={item.title}><div className="update-meta"><b>{item.date}</b><span>{item.status}</span></div><h2>{item.title}</h2><p>{item.en}</p><p lang="vi">{item.vi}</p><a href={SOURCES[item.source]} target="_blank" rel="noreferrer">{item.agency} · {item.section} <ArrowSquareOut size={13} /></a></article>)}</div><p className="source-limit">Sources checked 05 Oct 2026. This is a dated review; future changes need rechecking. / Đối chiếu ngày 05/10/2026; cần kiểm tra lại nếu có thay đổi sau ngày này.</p></details>
  </section>;
}

export function FilingNotes({ assessmentDate }) {
  const policy = policyForFiling(assessmentDate);
  return <aside className="filing-notes" aria-label="Filing date requirements"><strong>Filing-date checks / Kiểm tra theo ngày nộp · {assessmentDate}</strong>
    <p>{policy.revisedGuideline ? "The published 2027 guideline applies. Review continuous HSP points, household income, pension prospects, conduct, absences and applicable language/family factors." : "The general 2027 revision has not yet started for this filing date. Review the published changes before choosing a later filing date."}</p>
    <p lang="vi">{policy.revisedGuideline ? "Áp dụng hướng dẫn 2027: rà soát điểm HSP liên tục, thu nhập hộ, triển vọng lương hưu, hạnh kiểm, vắng mặt và yếu tố ngôn ngữ/gia đình tương ứng." : "Chưa áp dụng chung hướng dẫn 2027 cho ngày nộp này; cần xem thay đổi trước khi chọn ngày nộp muộn hơn."}</p>
    {policy.pendingIncomeReview && <p className="transition-note">Income/public-burden provisions also apply if this application was still pending on 01 Oct 2026. / Quy định thu nhập/gánh nặng công áp dụng nếu hồ sơ còn đang xét ngày 01/10/2026.</p>}
    <p>{policy.threeYearTreatment === "accepted" ? "A 3-year residence permit is treated as the longest period for filings through 31 Mar 2027." : "A 3-year permit is no longer automatically sufficient. Transition requires holding it on 31 Mar 2027, a first filing from 1 Apr 2027, and a decision within that same permit's validity."}</p>
    <p lang="vi">{policy.threeYearTreatment === "accepted" ? "Thời hạn cư trú 3 năm được coi là dài nhất cho hồ sơ nộp đến 31/03/2027." : "Thời hạn 3 năm không tự động đủ: phải có ngày 31/03/2027, nộp lần đầu từ 01/04/2027 và được quyết định trước khi chính thời hạn đó hết."}</p>
    <p>Standard fee on approval: <b>¥{policy.standardFee.toLocaleString("en-US")}</b>. <a href={SOURCES.reducedFee} target="_blank" rel="noreferrer">Check reduction eligibility</a>. PR filing does not extend your current stay; renew separately before expiry. / Nộp PR không gia hạn cư trú; phải làm thủ tục gia hạn riêng trước khi hết hạn.</p>
    <a href={SOURCES.guideline} target="_blank" rel="noreferrer">ISA revision & transition clauses <ArrowSquareOut size={13} /></a> · <a href={SOURCES.application} target="_blank" rel="noreferrer">ISA application procedure <ArrowSquareOut size={13} /></a>
  </aside>;
}
