export const KEY='jlpt-n1-skills-v1';
export function cleanProgress(raw){const p=raw?.format===KEY?raw.state:raw;return {items:p?.items&&typeof p.items==='object'&&!Array.isArray(p.items)?Object.fromEntries(Object.entries(p.items).filter(([k,v])=>k.length<240&&v&&typeof v==='object').map(([k,v])=>[k,{attempts:Math.max(0,Number(v.attempts)||0),correct:Math.max(0,Number(v.correct)||0),last:['correct','wrong','again','hard','good'].includes(v.last)?v.last:'again',due:Number(v.due)||0,streak:Math.max(0,Number(v.streak)||0),seconds:Math.max(0,Number(v.seconds)||0),note:typeof v.note==='string'?v.note.slice(0,4000):''}])):{},session:validSession(p?.session)?{skill:p.session.skill,ids:p.session.ids,index:p.session.index,startedAt:Number(p.session.startedAt)||Date.now(),results:Object.fromEntries(Object.entries(p.session.results).filter(([id,v])=>p.session.ids.includes(id)&&v&&typeof v==='object').map(([id,v])=>[id,{result:['correct','wrong','again','hard','good'].includes(v.result)?v.result:'wrong',confidence:v.confidence==='confident'?'confident':'unsure',seconds:Math.max(0,Number(v.seconds)||0),response:Array.isArray(v.response)?v.response.filter(x=>['string','number'].includes(typeof x)).slice(0,20):[]}]))}:null,migratedLegacy:!!p?.migratedLegacy,history:Array.isArray(p?.history)?p.history.slice(-60).filter(v=>v&&typeof v==='object').map(v=>({date:Number(v.date)||0,skill:typeof v.skill==='string'?v.skill.slice(0,80):'',count:Math.max(0,Number(v.count)||0),seconds:Math.max(0,Number(v.seconds)||0),correct:Math.max(0,Number(v.correct)||0),scored:Math.max(0,Number(v.scored)||0)})):[]};}
export function validSession(s){return s&&typeof s.skill==='string'&&Array.isArray(s.ids)&&s.ids.length<=20&&s.ids.every(v=>typeof v==='string')&&Number.isInteger(s.index)&&s.index>=0&&s.index<s.ids.length&&s.results&&typeof s.results==='object';}
export function plan(questions,items,skill,count=10,mode='all',now=Date.now(),random=Math.random){const pool=questions.filter(q=>(skill==='all'||q.skill===skill)&&(mode!=='review'||items[q.id]&&items[q.id].due<=now));return pool.map(q=>({q,r:random(),rank:items[q.id]?.last==='wrong'||items[q.id]?.last==='again'?0:items[q.id]&&items[q.id].due<=now?1:!items[q.id]?2:3})).sort((a,b)=>a.rank-b.rank||a.r-b.r).slice(0,Math.min(20,count)).map(v=>v.q.id);}
export function record(items,id,result,confidence,seconds,now=Date.now()){const old=items[id]||{};const positive=result==='correct'||result==='good';const streak=positive&&confidence!=='unsure'?(old.streak||0)+1:0;const days=streak>=4?7:streak>=3?3:streak>=2?1:0;return {...old,attempts:(old.attempts||0)+1,correct:(old.correct||0)+(result==='correct'?1:0),last:result,streak,due:now+(positive&&confidence!=='unsure'?(days?days*86400000:21600000):600000),seconds:(old.seconds||0)+seconds};}
export function skillStats(questions,items,skill,now=Date.now()){const qs=questions.filter(q=>q.skill===skill), seen=qs.filter(q=>items[q.id]);const scored=seen.filter(q=>q.mode!=='recall');const attempts=scored.reduce((n,q)=>n+items[q.id].attempts,0),correct=scored.reduce((n,q)=>n+items[q.id].correct,0);return{total:qs.length,seen:seen.length,due:seen.filter(q=>items[q.id].due<=now).length,stable:seen.filter(q=>items[q.id].streak>=2&&items[q.id].due>now).length,accuracy:attempts?Math.round(correct/attempts*100):null};}

export function migrateLegacy(state,library,legacy={},cards={}){
 if(state.migratedLegacy)return state;
 const ids=new Set(library.questions.map(q=>q.id)),progress=legacy.progress?.jlpt||legacy.jlpt||{},items={...state.items};
 for(const [old,v]of Object.entries(progress.learning||{})){
  const id=library.aliases?.[old]||old;if(!ids.has(id)||items[id]||!v||typeof v!=='object')continue;
  items[id]={attempts:Math.max(0,Number(v.attempts)||0),correct:Math.max(0,Number(v.correctCount)||0),last:v.lastOutcome==='correct'?'correct':'wrong',due:Date.parse(v.dueAt)||0,streak:Math.max(0,Number(v.correctStreak)||0),seconds:Math.max(0,(Number(v.averageTimeMs)||0)*(Number(v.attempts)||0)/1000),note:''};
 }
 if(cards.v===1&&cards.n===107)for(const [field,last]of [['known','good'],['unknown','again']])for(const i of Array.isArray(cards[field])?cards[field]:[]){if(!Number.isInteger(i)||i<0||i>=107)continue;const old=`n1:n1-grammar-flashcards:${i}`,id=library.aliases?.[old]||old;if(ids.has(id)&&!items[id])items[id]={attempts:0,correct:0,last,due:0,streak:0,seconds:0,note:''};}
 return {...state,items,migratedLegacy:true};
}
