export const KEY='jlpt-n1-skills-v1';
export function expandSkillIndex(index){
 if(!index.questionFormat)return index;
 if(index.questionFormat!=='skill-tuples-v1'||!Array.isArray(index.questionModes)||!Array.isArray(index.skills)||!Array.isArray(index.questions))throw Error('Chỉ mục kỹ năng không hợp lệ');
 return {...index,questions:index.questions.map(row=>{if(!Array.isArray(row)||row.length!==3||typeof row[0]!=='string'||!Number.isInteger(row[1])||!Number.isInteger(row[2])||!index.skills[row[1]]||!index.questionModes[row[2]])throw Error('Chỉ mục kỹ năng không hợp lệ');return{id:row[0],skill:index.skills[row[1]].id,mode:index.questionModes[row[2]]}})};
}
export function cleanProgress(raw){const p=raw?.format===KEY?raw.state:raw;return {items:p?.items&&typeof p.items==='object'&&!Array.isArray(p.items)?Object.fromEntries(Object.entries(p.items).filter(([k,v])=>k.length<240&&v&&typeof v==='object').map(([k,v])=>[k,{attempts:Math.max(0,Number(v.attempts)||0),correct:Math.max(0,Number(v.correct)||0),last:['correct','wrong','again','hard','good'].includes(v.last)?v.last:'again',due:Number(v.due)||0,streak:Math.max(0,Number(v.streak)||0),seconds:Math.max(0,Number(v.seconds)||0),note:typeof v.note==='string'?v.note.slice(0,4000):'',...(typeof v.firstCorrect==='boolean'?{firstCorrect:v.firstCorrect}:{}),...(v.legacyReviewed?{legacyReviewed:true}:{})}])):{},session:validSession(p?.session)?{skill:p.session.skill,mode:['all','scored','recall','recall-review','review'].includes(p.session.mode)?p.session.mode:'all',ids:p.session.ids,index:p.session.index,startedAt:Number(p.session.startedAt)||Date.now(),drafts:Object.fromEntries(Object.entries(p.session.drafts&&typeof p.session.drafts==='object'?p.session.drafts:{}).filter(([id,v])=>p.session.ids.includes(id)&&v&&typeof v==='object').map(([id,v])=>[id,{response:Array.isArray(v.response)?v.response.filter(x=>['string','number'].includes(typeof x)).slice(0,20):[],confidence:v.confidence==='unsure'?'unsure':'confident'}])),results:Object.fromEntries(Object.entries(p.session.results).filter(([id,v])=>p.session.ids.includes(id)&&v&&typeof v==='object').map(([id,v])=>[id,{result:['correct','wrong','again','hard','good'].includes(v.result)?v.result:'wrong',confidence:v.confidence==='confident'?'confident':'unsure',seconds:Math.max(0,Number(v.seconds)||0),response:Array.isArray(v.response)?v.response.filter(x=>['string','number'].includes(typeof x)).slice(0,20):[]}]))}:null,migratedLegacy:!!p?.migratedLegacy,history:Array.isArray(p?.history)?p.history.slice(-60).filter(v=>v&&typeof v==='object').map(v=>({date:Number(v.date)||0,skill:typeof v.skill==='string'?v.skill.slice(0,80):'',count:Math.max(0,Number(v.count)||0),seconds:Math.max(0,Number(v.seconds)||0),correct:Math.max(0,Number(v.correct)||0),scored:Math.max(0,Number(v.scored)||0)})):[]};}
export function validSession(s){return s&&typeof s.skill==='string'&&Array.isArray(s.ids)&&s.ids.length<=20&&s.ids.every(v=>typeof v==='string')&&Number.isInteger(s.index)&&s.index>=0&&s.index<s.ids.length&&s.results&&typeof s.results==='object';}
export function plan(questions,items,skill,count=10,mode='all',now=Date.now(),random=Math.random){const pool=questions.filter(q=>(skill==='all'||q.skill===skill)&&(!['review','recall-review'].includes(mode)||items[q.id]&&(items[q.id].attempts>0||items[q.id].legacyReviewed)&&items[q.id].due<=now));return pool.map(q=>({q,r:random(),rank:(items[q.id]?.attempts>0||items[q.id]?.legacyReviewed)&&(items[q.id]?.last==='wrong'||items[q.id]?.last==='again')?0:(items[q.id]?.attempts>0||items[q.id]?.legacyReviewed)&&items[q.id].due<=now?1:!(items[q.id]?.attempts>0||items[q.id]?.legacyReviewed)?2:3})).sort((a,b)=>a.rank-b.rank||a.r-b.r).slice(0,Math.min(20,count)).map(v=>v.q.id);}
export function record(items,id,result,confidence,seconds,now=Date.now()){const old=items[id]||{};const positive=result==='correct'||result==='good';const streak=positive&&confidence!=='unsure'?(old.streak||0)+1:0;const days=streak>=4?7:streak>=3?3:streak>=2?1:0;return {...old,...(!old.attempts&&['correct','wrong'].includes(result)?{firstCorrect:result==='correct'}:{}),attempts:(old.attempts||0)+1,correct:(old.correct||0)+(result==='correct'?1:0),last:result,streak,due:now+(positive&&confidence!=='unsure'?(days?days*86400000:21600000):600000),seconds:(old.seconds||0)+seconds};}
export function skillStats(questions,items,skill,now=Date.now()){const qs=questions.filter(q=>skill==='all'||q.skill===skill),seen=qs.filter(q=>items[q.id]&&(items[q.id].attempts>0||items[q.id].legacyReviewed)),scored=seen.filter(q=>q.mode!=='recall'),first=scored.filter(q=>typeof items[q.id].firstCorrect==='boolean'),attempts=scored.reduce((n,q)=>n+items[q.id].attempts,0),correct=scored.reduce((n,q)=>n+items[q.id].correct,0);return{total:qs.length,seen:seen.length,due:seen.filter(q=>items[q.id].due<=now).length,stable:seen.filter(q=>items[q.id].streak>=2&&items[q.id].due>now).length,accuracy:attempts?Math.round(correct/attempts*100):null,samples:attempts,firstAccuracy:first.length?Math.round(first.filter(q=>items[q.id].firstCorrect).length/first.length*100):null,firstSamples:first.length};}

export function migrateLegacy(state,library,legacy={},cards={}){
 if(state.migratedLegacy)return state;
 const ids=new Set(library.questions.map(q=>q.id)),progress=legacy.progress?.jlpt||legacy.jlpt||{},items={...state.items};
 for(const [old,v]of Object.entries(progress.learning||{})){
  const id=library.aliases?.[old]||old;if(!ids.has(id)||items[id]||!v||typeof v!=='object')continue;
  items[id]={attempts:Math.max(0,Number(v.attempts)||0),correct:Math.max(0,Number(v.correctCount)||0),last:v.lastOutcome==='correct'?'correct':'wrong',due:Date.parse(v.dueAt)||0,streak:Math.max(0,Number(v.correctStreak)||0),seconds:Math.max(0,(Number(v.averageTimeMs)||0)*(Number(v.attempts)||0)/1000),note:''};
 }
 if(cards.v===1&&cards.n===107)for(const [field,last]of [['known','good'],['unknown','again']])for(const i of Array.isArray(cards[field])?cards[field]:[]){if(!Number.isInteger(i)||i<0||i>=107)continue;const old=`n1:n1-grammar-flashcards:${i}`,id=library.aliases?.[old]||old;if(ids.has(id)&&!items[id])items[id]={attempts:0,correct:0,last,due:0,streak:0,seconds:0,note:'',legacyReviewed:true};}
 return {...state,items,migratedLegacy:true};
}

export function sessionPool(questions,mode){return questions.filter(q=>mode.startsWith('recall')?q.mode==='recall':q.mode!=='recall');}
export function sessionSummary(session,questions){const modes=new Map(questions.map(q=>[q.id,q.mode]));let cards=0,scored=0,correct=0;for(const[id,v]of Object.entries(session.results)){if(modes.get(id)==='recall'){cards++;continue;}if(['correct','wrong'].includes(v.result)){scored++;correct+=v.result==='correct'?1:0;}}return{cards,scored,correct,cardsOnly:session.ids.every(id=>modes.get(id)==='recall')};}
